### ISSUE TITLE
[bug] AP of 1.0 should have min p-value

### ISSUE THREAD

**Issue by alxndrkalinin** [cytomining/copairs#49]
When calculated AP is 1.0, corresponding p-value is too large.

For example, for 2 positive profiles, 16 controls, null size 1000, and AP = 1, p-value = 0.061938, which is incorrect, because the proportion of null to the right of the 1.0 should be 0, and p-value [should](https://github.com/cytomining/copairs/blob/11570eb5e03d908e344bb8f7f90940e6dac603e3/src/copairs/compute.py#L155) be `p=(num + 1) / (null_size + 1) = 1/1001 = ~0.000999`

**Comment by shntnu** [comment]
> For example, for 2 positive profiles, 16 controls, null size 1000, and AP = 1, p-value = 0.061938, which is incorrect, because the proportion of null to the right of the 1.0 should be 0, and p-value [should](https://github.com/cytomining/copairs/blob/11570eb5e03d908e344bb8f7f90940e6dac603e3/src/copairs/compute.py#L155) be `p=(num + 1) / (null_size + 1) = 1/1001 = ~0.000999`


I'm guessing here you had `num` =  0.061938 * 1001 - 1 = 61? That is, you ended up with 61 1's in the null?

**Comment by alxndrkalinin** [comment]
Ah, I thought more about this but forgot to comment here.

With 1 out of 2 replicates being a query, retrieving another one against 16 controls makes 17 possible binary rank list orders. When we generate 1,000 random samples, we produce `1000/17=~58.8` occurrences of each unique order, including the ideal scenario with `AP=1.0`, which is what end up happening, as @shntnu said above. In this case, getting a p-value below 0.05 is not possible with the proportion of the null having to be strictly greater than a statistic. However, if we choose `>=`, then we do not account for uncertainty of getting exactly the value from the null, which given coarse nulls like the above seems very generous (we'd give up 1/17 of the null).

This has to do with test resolution. To be able to get a `p<0.05`, the null should have enough distinct values in it to differentiate what's above it's 95%, i.e. > 20 unique values. Given M replicates and N controls the number of unique rankings is calculated as `N+M-1 choose M-1` and should be at least 21 to make it possible to get `p<0.05`.

This in part motivated simulations with different numbers or replicates and controls in the metrics paper (section `Simulations and comparison with mp-value` and `Figure 2`). As shown there, fraction retrieved is 0 for 2 replicates with either 8 or 16 controls (because we need at least 20), but with 3 replicates even 8 controls is enough (`8+3-1 choose 3-1 = 45`). The conclusion so far is: (a) do not use 2 replicates in experiments, (b) if you did, use all possible controls, (c) if that's not enough, then maybe retrieve against all other perturbations instead.

**Comment by shntnu** [comment]
> In this case, getting a p-value below 0.05 is not possible with the proportion of the null having to be strictly greater than the statistic.

I am confused about 2 things

(1) 
# null values > 1 == 0
# null values >= 1 == ~59

but IIUC you are saying that 

# null values > 1 == ~59?

(2) Are we still doing the +1 in the numerator and denominator?

Looks like we still are https://github.com/alxndrkalinin/copairs/blob/900c807f3b440abdc57de4a4b0d11c7ac6c65126/src/copairs/compute.py#L155
which is good but wasn't 100% sure given that the example you gave below (from the gdoc) did not have +1 i num and denom (but maybe you skipped that because you were just giving a ballpark?)

> 1 out 2 pos of is a query, so rank list size is 16 neg + 1 pos = total 17 possible combinations, so there will be 1000/17=~59 values of 1 in the null, and min p-value using `>` is 59/1000=~0.059

**Comment by alxndrkalinin** [comment]
Yes, sorry – there was a typo in my comment, I confused `>` and `>=` (updated my previous comment).

1. I agree this is correct:
num. null values > 1 == 0
num. null values >= 1 == ~59

This is not correct:
num. null values > 1 == ~59

2. Yes, we do use correction, and also for all figures in the paper we [used](https://github.com/alxndrkalinin/copairs/blob/900c807f3b440abdc57de4a4b0d11c7ac6c65126/src/copairs/compute.py#L154C1-L154C1) `>=` by default.

So my gdoc comment should be
> 1 out 2 pos of is a query, so rank list size is 16 neg + 1 pos = total 17 possible combinations, so there will be 1000/17=~59 values of 1 in the null, and min p-value using >= is 59/1000=~0.059

Which with correction becomes `60/1001=~0.0599`

**Comment by shntnu** [comment]
> However, if we choose `>`, then we do not account for uncertainty of getting exactly the value from the null, which given coarse nulls like the above **seems very generous (we'd give up 1/17 of the null).**

Could you clarify what you mean here in the part highlighted @alxndrkalinin ?

In Slack, you favored `>` over `>=` but sounds like you favor `>=` (and that's what you've used in the paper?)

> After more consideration, I’m leaning towards calling it a test design decision rather than a bug. Different sources suggest using either proportion of null greater or greater-or-equal than the statistic value and p-value normalizations also differ (e.g., p=(num + 1) / (null_size + 1) vs p=(num + 1) / null_size). For our use cases, the number of replicates and controls combined may be much smaller than the null size, which leads to multiple repetitive null values (e.g., 0.25, 0.25, 0.5, 0.5, 0.75, 0.75, 1.0, 1.0) and, consequently, larger p-values (if we use >= ) that often cannot in principle be less than a usual cutoff of 0.05. Since defending a choice of even higher cutoff value sounds even more controversial, **I’d argue we should use strict > as a default, but also give user a choice if they want to change it to >= as John suggested**

**Comment by alxndrkalinin** [comment]
Yes, I think went the full circle from switching to `>` and then going back to `>=` :D

I was thinking about it similarly to Fig. 1 in [Knijnenburg et al.](https://doi.org/10.1093/bioinformatics/btp211): let's plot a null CDF that we're approximating with permutations. When the number of possible permutations (N+M-1 choose M-1) is small, this step-wise approximation is quite coarse (which is basically a trade-off for being non-parametric and not trying to fit a distribution) and does not have enough resolution to represent the right tail of the CDF accurately enough (X axis is binned and the bin size is too large) for us to judge if a point on X axis is above 95th percentile or not.  So when we do get AP=1, it corresponds to the last bin on the X axis, and we can choose to either ignore (using `>`) the red shaded part when CDR and ECDF are different or account for it (using `>=`). The former is probably too optimistic and the latter is too conservative, and I suggested we should use more conservative approach to reflect the poor resolution (read, low replicates + controls number).

![cdf](https://github.com/cytomining/copairs/assets/1107762/7d5bb2fd-ea77-43c6-8009-3f873d9252d1)

**Comment by shntnu** [comment]
Thanks @alxndrkalinin!

This is very helpful.   (but we should get excited if we get say 50 heads in a row)

For my notes: 

`>` is wrong because say, with two coin tosses,

1. prob of getting >= 2 heads is 1/4  (p value  = 0.25)
2. prob of getting > 2 heads is 0 (p value  = 0)

2 is right
